/**
 * Phase 0.c.8 — BSM vs QuantLib parity test.
 *
 * Reads tests/fixtures/bsm-quantlib-golden.json (5,040 rows generated by
 * QuantLib's AnalyticEuropeanEngine) and asserts our JS BSM implementation
 * ([src/lib/backtest/bsm-pricing.ts]) agrees with the reference within the
 * tolerance declared in the fixture.
 *
 * If this test fails: either our BSM has a regression, or the fixture was
 * regenerated with a different QuantLib version or config. Investigate the
 * specific failing rows first; do NOT loosen tolerances blindly.
 *
 * See tests/fixtures/bsm-quantlib-golden.README.md for grid and config.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { bsmPrice, bsmDelta } from '../src/lib/backtest/bsm-pricing';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FIXTURE_PATH = path.resolve(__dirname, 'fixtures/bsm-quantlib-golden.json');

interface GoldenRow {
  S: number;
  K: number;
  T: number;
  sigma: number;
  r: number;
  isCall: boolean;
  qlPrice: number;
  qlDelta: number;
}

interface GoldenFile {
  quantlibVersion: string;
  generatedAt: string;
  /** Phase 0.c.8 round-2: pricing convention the fixture was generated with.
   *  Pinned so a future regeneration that drifted on any of these would
   *  fail the config assertion below before the grid scan runs. */
  config?: {
    dividendYield: number;
    rateCompounding: string;
    dayCount: string;
    exerciseStyle: string;
    pricingEngine: string;
    evaluationDate: string;
  };
  tolerance: { priceAbs: number; priceRel: number; deltaAbs: number };
  grid: GoldenRow[];
}

/**
 * Hardcoded anchor values independent of the committed JSON. If someone
 * regenerates the fixture with the wrong QuantLib config and the fixture
 * silently self-authenticates, these anchors still fail. Values computed
 * by QuantLib 1.42.1 with the pinned convention.
 */
const HARDCODED_ANCHORS: Array<{
  label: string;
  S: number; K: number; T: number; sigma: number; r: number; isCall: boolean;
  qlPrice: number; qlDelta: number;
}> = [
  // Values hand-transcribed from QuantLib 1.42.1 output (AnalyticEuropeanEngine,
  // q=0, continuous r, Actual/365Fixed). If these ever fail, our BSM has
  // drifted AND the fixture regen can't hide it: these are independent.
  {
    label: 'ATM 30D call σ=20 r=4',
    S: 100, K: 100, T: 30 / 365, sigma: 0.20, r: 0.04, isCall: true,
    qlPrice: 2.4512622091842386, qlDelta: 0.5342697035912664,
  },
  {
    label: 'ATM 30D put σ=20 r=4',
    S: 100, K: 100, T: 30 / 365, sigma: 0.20, r: 0.04, isCall: false,
    qlPrice: 2.1230349332277902, qlDelta: -0.4657302964087338,
  },
  {
    label: 'ATM 1Y call σ=80 r=4',
    S: 100, K: 100, T: 1.0, sigma: 0.80, r: 0.04, isCall: true,
    qlPrice: 32.47155047377887, qlDelta: 0.67364477971208,
  },
  {
    label: 'OTM 7D call S=100 K=115 σ=30 r=2',
    S: 100, K: 115, T: 7 / 365, sigma: 0.30, r: 0.02, isCall: true,
    qlPrice: 0.00045960336599254486, qlDelta: 0.0004279326578214504,
  },
  {
    label: 'ITM 180D put S=100 K=130 σ=30 r=5',
    S: 100, K: 130, T: 180 / 365, sigma: 0.30, r: 0.05, isCall: false,
    qlPrice: 28.36708001560328, qlDelta: -0.846840893803092,
  },
];

function loadFixture(): GoldenFile {
  const raw = fs.readFileSync(FIXTURE_PATH, 'utf-8');
  return JSON.parse(raw) as GoldenFile;
}

interface Divergence {
  row: GoldenRow;
  ourValue: number;
  diff: number;
  tolerance: number;
  kind: 'price' | 'delta';
}

function checkAll(fixture: GoldenFile): Divergence[] {
  const { priceAbs, priceRel, deltaAbs } = fixture.tolerance;
  const divergences: Divergence[] = [];
  for (const row of fixture.grid) {
    const ourPrice = bsmPrice(row.S, row.K, row.T, row.sigma, row.r, row.isCall);
    const priceTol = Math.max(priceAbs, priceRel * Math.abs(row.qlPrice));
    const priceDiff = Math.abs(ourPrice - row.qlPrice);
    if (priceDiff > priceTol || !Number.isFinite(ourPrice)) {
      divergences.push({ row, ourValue: ourPrice, diff: priceDiff, tolerance: priceTol, kind: 'price' });
    }
    const ourDelta = bsmDelta(row.S, row.K, row.T, row.sigma, row.r, row.isCall);
    const deltaDiff = Math.abs(ourDelta - row.qlDelta);
    if (deltaDiff > deltaAbs || !Number.isFinite(ourDelta)) {
      divergences.push({ row, ourValue: ourDelta, diff: deltaDiff, tolerance: deltaAbs, kind: 'delta' });
    }
  }
  return divergences;
}

function formatDivergence(d: Divergence): string {
  const { row } = d;
  const qlValue = d.kind === 'price' ? row.qlPrice : row.qlDelta;
  const inputs =
    `S=${row.S} K=${row.K} T=${row.T.toFixed(5)} σ=${row.sigma} r=${row.r} ` +
    (row.isCall ? 'call' : 'put');
  return `${d.kind} ${inputs} ql=${qlValue.toFixed(6)} ours=${d.ourValue.toFixed(6)} diff=${d.diff.toExponential(2)} tol=${d.tolerance.toExponential(2)}`;
}

describe('BSM vs QuantLib parity (Phase 0.c.8)', () => {
  it('agrees with QuantLib on every grid row within fixture tolerance', () => {
    const fixture = loadFixture();
    expect(fixture.grid.length).toBeGreaterThan(100); // sanity

    const divergences = checkAll(fixture);

    if (divergences.length > 0) {
      const summary = divergences.slice(0, 20).map(formatDivergence).join('\n  ');
      const more = divergences.length > 20 ? `\n  ... and ${divergences.length - 20} more.` : '';
      throw new Error(
        `${divergences.length}/${fixture.grid.length * 2} BSM values diverge from QuantLib (fixture QL ${fixture.quantlibVersion}):\n  ${summary}${more}\n` +
        `See tests/fixtures/bsm-quantlib-golden.README.md.`,
      );
    }
  });

  it('fixture has the expected grid size (5,040 rows)', () => {
    const fixture = loadFixture();
    expect(fixture.grid.length).toBe(5040);
    // Both call and put coverage.
    const calls = fixture.grid.filter(r => r.isCall).length;
    const puts = fixture.grid.length - calls;
    expect(calls).toBe(2520);
    expect(puts).toBe(2520);
  });

  it('fixture tolerance is the documented policy', () => {
    const fixture = loadFixture();
    expect(fixture.tolerance.priceAbs).toBe(1e-4);
    expect(fixture.tolerance.priceRel).toBe(1e-5);
    expect(fixture.tolerance.deltaAbs).toBe(1e-4);
  });

  it('records the QuantLib version the fixture was generated with', () => {
    const fixture = loadFixture();
    expect(fixture.quantlibVersion).toMatch(/^\d+\.\d+(\.\d+)?$/);
  });

  // ── Edge-case spot checks that the grid may undersample ──
  // These hit specific numerical corners: 1-DTE deep OTM, very short T,
  // very high vol, r=0. They are computed against QuantLib values stored
  // in the fixture — we look them up rather than hardcoding.

  it('1-DTE deep OTM call has near-zero but positive price matching QuantLib', () => {
    const fixture = loadFixture();
    const row = fixture.grid.find(r =>
      r.isCall && r.S === 100 && r.K === 130 && Math.abs(r.T - 1 / 365) < 1e-9 && r.sigma === 0.2 && r.r === 0.04);
    expect(row, 'fixture must contain S=100 K=130 1-DTE σ=0.2 r=0.04 call').toBeTruthy();
    if (row) {
      expect(row.qlPrice).toBeGreaterThan(0);
      expect(row.qlPrice).toBeLessThan(0.1);
      const ours = bsmPrice(row.S, row.K, row.T, row.sigma, row.r, row.isCall);
      expect(Math.abs(ours - row.qlPrice)).toBeLessThan(1e-4);
    }
  });

  it('deep ITM call delta ≈ 1', () => {
    const fixture = loadFixture();
    const row = fixture.grid.find(r =>
      r.isCall && r.S === 100 && r.K === 70 && r.T === 90 / 365 && r.sigma === 0.1 && r.r === 0.04);
    expect(row).toBeTruthy();
    if (row) {
      expect(row.qlDelta).toBeGreaterThan(0.99);
      const ours = bsmDelta(row.S, row.K, row.T, row.sigma, row.r, row.isCall);
      expect(Math.abs(ours - row.qlDelta)).toBeLessThan(1e-4);
    }
  });

  it('high-vol ATM 365-DTE put has finite price matching QuantLib', () => {
    const fixture = loadFixture();
    const row = fixture.grid.find(r =>
      !r.isCall && r.S === 100 && r.K === 100 && r.T === 365 / 365 && r.sigma === 0.8 && r.r === 0.04);
    expect(row).toBeTruthy();
    if (row) {
      expect(Number.isFinite(row.qlPrice)).toBe(true);
      const ours = bsmPrice(row.S, row.K, row.T, row.sigma, row.r, row.isCall);
      expect(Math.abs(ours - row.qlPrice)).toBeLessThan(
        Math.max(1e-4, 1e-5 * Math.abs(row.qlPrice)),
      );
    }
  });

  it('T=0 intrinsic-only branch is handled identically to QuantLib payoff', () => {
    // Our bsmPrice returns intrinsic for T<=0. QuantLib's engine short-circuits
    // the same way. This test doesn't go through the fixture — it's a direct
    // assertion on the boundary behavior of our function.
    expect(bsmPrice(100, 90, 0, 0.2, 0.04, true)).toBe(10); // ITM call
    expect(bsmPrice(100, 110, 0, 0.2, 0.04, true)).toBe(0); // OTM call
    expect(bsmPrice(100, 110, 0, 0.2, 0.04, false)).toBe(10); // ITM put
    expect(bsmPrice(100, 90, 0, 0.2, 0.04, false)).toBe(0); // OTM put
  });

  // Phase 0.c.8 round-2 F3: hardcoded anchors + fixture config assertion.
  // A future regeneration that changed dividend yield, day-count, or rate
  // compounding would silently redefine truth in the grid. The anchors
  // below are QuantLib 1.42.1 outputs transcribed into source, so a bad
  // regeneration can't hide: the grid might pass but the anchors fail.

  it('fixture config pins the QuantLib pricing convention', () => {
    const fixture = loadFixture();
    expect(fixture.config, 'fixture.config must be present').toBeTruthy();
    expect(fixture.config!.dividendYield).toBe(0.0);
    expect(fixture.config!.rateCompounding).toBe('Continuous');
    expect(fixture.config!.dayCount).toBe('Actual/365Fixed');
    expect(fixture.config!.exerciseStyle).toBe('European');
    expect(fixture.config!.pricingEngine).toBe('AnalyticEuropeanEngine');
  });

  it('hardcoded QuantLib anchors — our BSM agrees with inline reference values', () => {
    const failures: string[] = [];
    for (const a of HARDCODED_ANCHORS) {
      const ourPrice = bsmPrice(a.S, a.K, a.T, a.sigma, a.r, a.isCall);
      const ourDelta = bsmDelta(a.S, a.K, a.T, a.sigma, a.r, a.isCall);
      const priceTol = Math.max(1e-4, 1e-5 * Math.abs(a.qlPrice));
      if (Math.abs(ourPrice - a.qlPrice) > priceTol) {
        failures.push(`${a.label}: price ours=${ourPrice.toFixed(6)} qlAnchor=${a.qlPrice.toFixed(6)}`);
      }
      if (Math.abs(ourDelta - a.qlDelta) > 1e-4) {
        failures.push(`${a.label}: delta ours=${ourDelta.toFixed(6)} qlAnchor=${a.qlDelta.toFixed(6)}`);
      }
    }
    if (failures.length > 0) {
      throw new Error(`Anchor mismatch:\n  ${failures.join('\n  ')}`);
    }
  });

  it('hardcoded anchors match the fixture — detects a drifted regeneration', () => {
    const fixture = loadFixture();
    const mismatches: string[] = [];
    for (const a of HARDCODED_ANCHORS) {
      const row = fixture.grid.find(r =>
        r.S === a.S && r.K === a.K && Math.abs(r.T - a.T) < 1e-9
        && r.sigma === a.sigma && r.r === a.r && r.isCall === a.isCall);
      if (!row) {
        mismatches.push(`${a.label}: not found in fixture`);
        continue;
      }
      if (Math.abs(row.qlPrice - a.qlPrice) > 1e-6) {
        mismatches.push(`${a.label}: fixture qlPrice=${row.qlPrice} anchor=${a.qlPrice}`);
      }
      if (Math.abs(row.qlDelta - a.qlDelta) > 1e-6) {
        mismatches.push(`${a.label}: fixture qlDelta=${row.qlDelta} anchor=${a.qlDelta}`);
      }
    }
    if (mismatches.length > 0) {
      throw new Error(
        `Fixture does not match hardcoded anchors — the regeneration may have used a ` +
        `different QuantLib version or pricing convention:\n  ${mismatches.join('\n  ')}`,
      );
    }
  });
});
