/**
 * Phase 0.c.9.B — CBOE BXM replication regression.
 *
 * Locks in the result of `scripts/replicate-bxm.ts` as committed in
 * `data/bxm-replication-results.json`. A failing assertion here means
 * the last run produced degraded correlation against the published CBOE
 * BXM series — either the replication script regressed, the simulator
 * regressed, or the committed JSON is stale (re-run the script before
 * investigating).
 *
 * The committed JSON carries 107 paired monthly cycles (2017-2026 SPY),
 * produced on 2026-04-19 with `simulateBuyWrite` at Phase 0.c.9.A.
 * Correlation on that run: 0.9575. Target: ≥ 0.85 (allows material
 * drift from engine changes without crying wolf on cosmetic deltas).
 */
import fs from 'fs';
import path from 'path';
import { describe, expect, it } from 'vitest';

const RESULTS_PATH = path.resolve(process.cwd(), 'data/bxm-replication-results.json');
const RESULTS_EXIST = fs.existsSync(RESULTS_PATH);

interface Pair { month: string; entryDate: string; exitDate: string; bxm: number; rep: number; residual: number; }
interface ResultsFile {
  summary: {
    window: { start: string; end: string; months: number };
    correlation: number;
    meanMonthlyReturn: { bxm: number; rep: number };
    annualizedReturnGap: number;
    residualSd: number;
    maxAbsResidual: number;
  };
  pairs: Pair[];
}

describe.skipIf(!RESULTS_EXIST)('CBOE BXM replication (Phase 0.c.9.B)', () => {
  const data = JSON.parse(fs.readFileSync(RESULTS_PATH, 'utf-8')) as ResultsFile;

  it('covers a meaningful number of monthly cycles', () => {
    expect(data.pairs.length).toBeGreaterThanOrEqual(60);
    expect(data.summary.window.months).toBe(data.pairs.length);
  });

  it('correlation with published BXM is ≥ 0.85', () => {
    // Cross-check the stored correlation by recomputing from the raw pairs.
    // Protects against stored-stat drift (if someone hand-edits the JSON).
    const recomputed = pearson(data.pairs.map(p => p.bxm), data.pairs.map(p => p.rep));
    expect(recomputed).toBeGreaterThanOrEqual(0.85);
    expect(Math.abs(recomputed - data.summary.correlation)).toBeLessThan(1e-6);
  });

  it('annualized return gap is within ±2% (dividend/fill drift only)', () => {
    // The simulator runs WITHOUT a dividendSchedule at present — empirical
    // gap ~0.4%/yr on SPY indicates the mechanics are right (BXM is a
    // total-return index including SPX dividends; SPY used as proxy has
    // physical dividends captured in the ORATS close-price series). A
    // larger gap would indicate a fill-model, roll-date, or notional bug.
    expect(Math.abs(data.summary.annualizedReturnGap)).toBeLessThan(0.02);
  });

  it('residual σ is modest (<2% monthly)', () => {
    // Month-to-month replication error. Anything much above 2% means
    // the replication is noisy relative to the ~4% monthly sd typical of
    // buy-write indices.
    expect(data.summary.residualSd).toBeLessThan(0.02);
  });

  it('rep return sign-flip destroys correlation (smoke test for spurious signal)', () => {
    // If the correlation were a fluke of common drift, inverting rep's
    // sign should still leave moderate correlation. If the signal is
    // real, inverting should flip it to strongly negative.
    const inverted = pearson(
      data.pairs.map(p => p.bxm),
      data.pairs.map(p => -p.rep),
    );
    expect(inverted).toBeLessThan(-0.5);
  });
});

describe.skipIf(RESULTS_EXIST)('BXM replication (skipped: results absent)', () => {
  it('notes that data/bxm-replication-results.json must be generated by scripts/replicate-bxm.ts', () => {
    console.warn('[0.c.9.B] data/bxm-replication-results.json not found; BXM replication test skipped.');
    expect(RESULTS_EXIST).toBe(false);
  });
});

function pearson(xs: number[], ys: number[]): number {
  const n = xs.length;
  if (n === 0 || n !== ys.length) return 0;
  const mx = xs.reduce((s, v) => s + v, 0) / n;
  const my = ys.reduce((s, v) => s + v, 0) / n;
  let num = 0, dx = 0, dy = 0;
  for (let i = 0; i < n; i++) {
    num += (xs[i] - mx) * (ys[i] - my);
    dx += (xs[i] - mx) ** 2;
    dy += (ys[i] - my) ** 2;
  }
  return dx > 0 && dy > 0 ? num / Math.sqrt(dx * dy) : 0;
}
