/**
 * strategy-campaign-e-signals.ts — Campaign E-Clean, Invocation 2 (ema3d + noNT signals)
 *
 * Pre-registered in .prompts/campaign-e-clean-preregistration.md (2026-04-17).
 *
 * Signal changes vs Invocation 1 (strategy-campaign-e.ts):
 *   - EMA34 rising over 3 days instead of 5 days
 *   - 12 tickers (drop NVDA + TSLA — "noNT" subset)
 *   - Everything else identical (SPY>EMA200, ticker>EMA55, EMA8>EMA13,
 *     0-5% band above EMA34, contangoPct<48)
 *
 * Rationale: the contaminated Campaign E v1 claimed these two changes
 * stacked with SimConfig changes produce a combined Sharpe of ~1.35. That
 * finding is not defensible because Campaign E v1 had holdout leakage and
 * post-hoc threshold reclassification. This invocation re-tests the signal
 * hypothesis under strict pre-registration.
 *
 * Base buildConfig() = Campaign D incumbent (d65-sl35-ts105).
 * 3 configVariants probe the specific stacks that Campaign E v1 claimed.
 *
 * ⚠️ Any change to variants, signals, tickers, or WFA must be paired with a
 *    new pre-registration. Do NOT edit this file during a running sweep.
 *
 * Run (writes to same leaderboard suffix as Invocation 1):
 *   AUTORESEARCH_LEADERBOARD_SUFFIX=campaign-e-clean \
 *     AUTORESEARCH_STRATEGY_FILENAME=strategy-campaign-e-signals.ts \
 *     AUTORESEARCH_MIN_OOS_TRADES=60 \
 *     npx tsx scripts/autoresearch/runner.ts
 */
import type { StrategyDefinition, TickerDataBundle, MarketContext, EntrySignal, SimConfig } from './types';
import { DEFAULT_LEAP_CONFIG } from '../../src/lib/backtest/option-sim';

// 12-ticker subset: drop NVDA + TSLA from the 14-ticker champion set
const CAMPAIGN_TICKERS_NO_NT = [
  'GLD', 'IWM', 'AAPL', 'MSFT', 'GOOG', 'AMZN', 'META',
  'JPM', 'GS', 'COST', 'UNH', 'NFLX',
];

export const strategy: StrategyDefinition = {
  name: 'ceC-ema3d-noNT-inc',
  tickers: CAMPAIGN_TICKERS_NO_NT,

  portfolio: {
    maxPositions: 4,
    maxPerTicker: 1,
    startingCapital: 10000,
  },

  wfa: {
    trainWindowDays: 252,
    forwardStepDays: 126,
    purgeGapDays: 10,
    mode: 'rolling' as const,
    holdoutCount: 5,
  },

  buildConfig(_ticker: string, _direction: 'CALL' | 'PUT'): SimConfig {
    return {
      ...DEFAULT_LEAP_CONFIG,
      mode: 'LEAP' as const,
      leapDeltaRange: [0.65, 0.80] as [number, number],
      leapDTERange: [180, 270] as [number, number],
      leapProfitTarget: 0.40,
      leapStopLoss: 0.35,
      leapTimeStopDTE: 105,
      monitoringIntervalDays: 1,
    };
  },

  generateSignals(data: TickerDataBundle, market: MarketContext): EntrySignal[] {
    const signals: EntrySignal[] = [];
    const ema8 = data.emas.get(8)!;
    const ema13 = data.emas.get(13)!;
    const ema34 = data.emas.get(34)!;
    const ema55 = data.emas.get(55)!;
    const ema200 = data.emas.get(200)!;
    const n = data.candles.length;

    for (let i = 60; i < n; i++) {
      const c = data.candles[i];

      if (ema8[i] <= 0 || ema13[i] <= 0) continue;
      // 3-day rising window (change vs Invocation 1)
      if (ema34[i] <= 0 || ema34[i - 3] <= 0) continue;
      if (ema55[i] <= 0 || ema200[i] <= 0) continue;

      const spy = market.spyByDate.get(c.date);
      if (!spy || !spy.ema200 || spy.ema200 <= 0) continue;

      if (spy.close <= spy.ema200) continue;
      if (c.close <= ema55[i]) continue;
      // 3-day rising window (change vs Invocation 1)
      if (!(ema8[i] > ema13[i] && ema34[i] > ema34[i - 3])) continue;

      const pct = (c.close - ema34[i]) / ema34[i];
      if (!(pct >= 0 && pct < 0.05)) continue;

      const regime = data.regimeByDate.get(c.date);
      if (regime && regime.contangoPct !== undefined && regime.contangoPct >= 48) continue;

      signals.push({
        ticker: data.ticker,
        date: c.date,
        direction: 'CALL',
        score: Math.round(100 - pct * 1000),
      });
    }

    return signals;
  },

  // Pre-registered 3-variant SimConfig sweep under the ema3d + noNT signal stack.
  configVariants: [
    // Signal + ticker change alone, SimConfig at incumbent
    { name: 'ceC-ema3d-noNT-inc', overrides: {} },

    // Plus ts150 (Campaign D's top-2 axes combined, now layered on new signals)
    { name: 'ceC-ema3d-noNT-sl35-ts150', overrides: { leapTimeStopDTE: 150 } },

    // Matches the contaminated-E iter-10 SimConfig (sl33 + ts150)
    { name: 'ceC-ema3d-noNT-sl33-ts150', overrides: { leapStopLoss: 0.33, leapTimeStopDTE: 150 } },
  ],
};
