//@version=6
// © MB+DFP v3.2 (Visual Indicator Only)
// v3.2: Direction-aware scoring, ATR-normalized momentum, 7-component composite
// Calibrated for 1.5wk–2mo swing options holding period

indicator("MB+DFP v3.2", shorttitle="MBDFP v3.2", overlay=true, max_bars_back=1500, max_boxes_count=500, max_lines_count=500, max_labels_count=500)

// ==========================================
// 1. VISUAL INDICATOR INPUTS
// ==========================================
mbGR = "Visuals: Market Bias"
ha_htf  = input.timeframe('', 'Timeframe', tooltip="Must be >= chart timeframe", group=mbGR, display=display.data_window)
ha_len  = input.int(20, 'Period',    group=mbGR, display=display.data_window)
ha_len2 = input.int(7, 'Smoothing', group=mbGR, display=display.data_window)
osc_len = input.int(7, "Oscillator Period", group=mbGR, display=display.data_window)
show_ha = input.bool(true,  "Show HA Candles",   inline='ha/mb display', group=mbGR, display=display.data_window)
show_mb = input.bool(true,  "Show Market Bias",   inline='ha/mb display', group=mbGR, display=display.data_window)
col_bull = input.color(color.lime, 'Color: Bullish', inline='bull/bear color', group=mbGR, display=display.data_window)
col_bear = input.color(color.red,  'Bearish',         inline='bull/bear color', group=mbGR, display=display.data_window)

emaGR    = "Visuals: EMA Stack"
show_stack = input.bool(true,         "Show EMA Stack", group=emaGR, display=display.data_window)
ema_len1  = input.int(8,  "EMA 1 Length", group=emaGR, display=display.data_window)
ema_len2  = input.int(21, "EMA 2 Length", group=emaGR, display=display.data_window)
ema_len3  = input.int(34, "EMA 3 Length", group=emaGR, display=display.data_window)
c_ema1    = input.color(color.yellow, "EMA 1 Color",    group=emaGR, display=display.data_window)
c_ema2    = input.color(color.orange, "EMA 2 Color",   group=emaGR, display=display.data_window)
c_ema3    = input.color(color.red,    "EMA 3 Color",   group=emaGR, display=display.data_window)



dfGR   = "Visuals: Delta Flow"
dfDist = input.int(0,  'Distance from Price', minval=-100, maxval=100, step=1, group=dfGR, display=display.data_window)
vpSH   = input.bool(true, 'Money Flow Profile', inline='mfp', group=dfGR, display=display.data_window)
mfpC   = input.color(color.new(#5288C4, 0), '', inline='mfp', group=dfGR, display=display.data_window)
npSH   = input.bool(true, 'Normalized', inline='mfp', group=dfGR, display=display.data_window)
spSH   = input.bool(true, 'Delta Profile', group=dfGR, display=display.data_window)
spPTY  = input.string('Bar Polarity', 'Polarity Method', options=['Bar Polarity', 'Bar Buying/Selling Pressure'], inline='pm', group=dfGR, display=display.data_window)
spBLC  = input.color(color.new(#5288C4, 0), '', inline='pm', group=dfGR, display=display.data_window)
spBRC  = input.color(color.new(#f7525f, 0), '', inline='pm', group=dfGR, display=display.data_window)
rpLN   = input.int(360, 'Lookback Length',         minval=10, maxval=1500, step=10,  group=dfGR, display=display.data_window)
rpNR   = input.int(25,  'Number of Rows',           minval=10, maxval=125,  step=5,   group=dfGR, display=display.data_window)
rpW    = input.int(17,  'Profile Width %',           minval=10, maxval=50,             group=dfGR, display=display.data_window) / 100
vpHO   = input.int(13,  'Profile Horizontal Offset',                                   group=dfGR, display=display.data_window)
vpLS   = input.string('Tiny',  'Profile Text',  options=['Auto','Tiny','Small','None'], group=dfGR, display=display.data_window)
vpLC   = input.bool(false, 'Currency', group=dfGR, display=display.data_window)
rpPL   = input.bool(false, 'Profile Price Levels', group=dfGR, display=display.data_window)
rpLS   = input.string('Small', 'Level Text Size', options=['Tiny','Small','Normal'],    group=dfGR, display=display.data_window)

// ==========================================
// 2. VISUAL CALCULATIONS
// ==========================================
indexHighTF = timeframe.in_seconds(ha_htf) == timeframe.in_seconds('') ? 0 : barstate.isrealtime ? 1 : 0
indexCurrTF = timeframe.in_seconds(ha_htf) == timeframe.in_seconds('') ? 0 : barstate.isrealtime ? 0 : 1

f_no_repaint_request(string _resolution, _expression) =>
    request.security(syminfo.tickerid, _resolution, _expression[indexHighTF])[indexCurrTF]

f_gTxtSz(_t) =>
    switch _t
        'Tiny'   => size.tiny
        'Small'  => size.small
        'Normal' => size.normal
        => size.auto

f_drawLabelX(_x, _y, _text, _style, _textcolor, _size, _tooltip) =>
    var lb = label.new(_x, _y, _text, xloc.bar_index, yloc.price, color(na), _style, _textcolor, _size, text.align_left, _tooltip)
    lb.set_xy(_x, _y), lb.set_text(_text), lb.set_tooltip(_tooltip), lb.set_textcolor(_textcolor)

// EMA Stack
v_ema1  = ta.ema(close, ema_len1)
v_ema2  = ta.ema(close, ema_len2)
v_ema3  = ta.ema(close, ema_len3)
plot(show_stack ? v_ema1  : na, "EMA 1",  color=c_ema1,  linewidth=2)
plot(show_stack ? v_ema2  : na, "EMA 2",  color=c_ema2, linewidth=2)
plot(show_stack ? v_ema3  : na, "EMA 3",  color=c_ema3, linewidth=2)



// Market Bias Visuals
mb_o = ta.ema(open, ha_len), mb_c = ta.ema(close, ha_len), mb_h = ta.ema(high, ha_len), mb_l = ta.ema(low, ha_len)
haclose  = f_no_repaint_request(ha_htf, (mb_o + mb_h + mb_l + mb_c) / 4)
xhaopen  = f_no_repaint_request(ha_htf, (mb_o + mb_c) / 2)
haopen   = na(xhaopen[1]) ? (mb_o + mb_c) / 2 : (xhaopen[1] + haclose[1]) / 2
hahigh   = math.max(mb_h, math.max(haopen, haclose))
halow    = math.min(mb_l, math.min(haopen, haclose))
o2 = f_no_repaint_request(ha_htf, ta.ema(haopen,  ha_len2))
c2 = f_no_repaint_request(ha_htf, ta.ema(haclose, ha_len2))
h2 = f_no_repaint_request(ha_htf, ta.ema(hahigh,  ha_len2))
l2 = f_no_repaint_request(ha_htf, ta.ema(halow,   ha_len2))
osc_bias   = 100 * (c2 - o2)
osc_smooth = ta.ema(osc_bias, osc_len)
sigcolor   = switch
    (osc_bias > 0) and (osc_bias >= osc_smooth) => color.new(col_bull, 35)
    (osc_bias > 0) and (osc_bias < osc_smooth)  => color.new(col_bull, 75)
    (osc_bias < 0) and (osc_bias <= osc_smooth) => color.new(col_bear, 35)
    (osc_bias < 0) and (osc_bias > osc_smooth)  => color.new(col_bear, 75)
    => color(na)
p_h = plot(h2, "Bias High", color=color(na), display=display.data_window, editable=false)
p_l = plot(l2, "Bias Low",  color=color(na), display=display.data_window, editable=false)
fill(p_l, p_h, show_mb ? sigcolor : na)
plotcandle(o2, h2, l2, c2, title='heikin smoothed', color=o2 > c2 ? col_bear : col_bull, display=show_ha ? display.pane : display.data_window, editable=false)

// Delta Flow Profile
type bar
    float o = open
    float h = high
    float l = low
    float c = close
    float v = volume
    int   i = bar_index

bar b    = bar.new()
nzV      = nz(b.v)
rpVST    = array.new<float>(rpNR, 0.)
rpVSB    = array.new<float>(rpNR, 0.)
rpVSD    = array.new<float>(rpNR, 0.)
var dRP  = array.new<box>()
var dPR  = array.new<line>()
var float pLST = na, var float pHST = na, var int sI = na, var color llC = na
bull = spPTY == 'Bar Polarity' ? b.c > b.o : (b.c - b.l) > (b.h - b.c)
rpS  = f_gTxtSz(rpLS), vpS = f_gTxtSz(vpLS)
adj_rpLN = last_bar_index > rpLN ? rpLN - 1 : last_bar_index
if b.i == last_bar_index - adj_rpLN
    sI   := b.i, pLST := b.l, pHST := b.h
else if b.i > last_bar_index - adj_rpLN
    pLST := math.min(b.l, pLST), pHST := math.max(b.h, pHST)
pSTP = (pHST - pLST) / rpNR

if barstate.islast and not na(nzV) and not timeframe.isseconds and adj_rpLN > 0 and pSTP > 0 and nzV > 0
    if dRP.size() > 0
        for i = 0 to dRP.size() - 1
            box.delete(dRP.shift())
    if dPR.size() > 0
        for i = 0 to dPR.size() - 1
            line.delete(dPR.shift())
    for bI = adj_rpLN to 0
        l_idx = 0
        _h = high[bI], _l = low[bI], _v = nzV[bI]
        for pLL = pLST to pHST - pSTP by pSTP
            if _h >= pLL and _l < pLL + pSTP
                vPOR = 0.0
                if _l >= pLL and _h > pLL + pSTP
                    vPOR := (pLL + pSTP - _l) / (_h - _l)
                else if _h <= pLL + pSTP and _l < pLL
                    vPOR := (_h - pLL) / (_h - _l)
                else if (_l >= pLL and _h <= pLL + pSTP)
                    vPOR := 1.0
                else
                    vPOR := pSTP / (_h - _l)
                rpVST.set(l_idx, rpVST.get(l_idx) + _v * vPOR * (pLST + (l_idx + .5) * pSTP))
                if bull[bI] and spSH
                    rpVSB.set(l_idx, rpVSB.get(l_idx) + _v * vPOR * (pLST + (l_idx + .5) * pSTP))
            l_idx += 1
    vtMX = rpVST.max()
    for l = 0 to rpNR - 1
        vtLV = rpVST.get(l), LpM = vtLV / vtMX, bbp = 2 * rpVSB.get(l) - vtLV
        rpVSD.set(l, rpVSD.get(l) + bbp * (bbp > 0 ? 1 : -1))
        if vpSH and npSH
            llC := color.from_gradient(LpM, 0, 1, color.new(mfpC, 93), color.new(mfpC, 53))
            sBI  = b.i + int(4 * adj_rpLN * rpW / 3) + dfDist
            dRP.push(box.new(sBI + 1 + vpHO, pLST + (l + .03) * pSTP, sBI + int(adj_rpLN * rpW / 3) + 3 + vpHO, pLST + (l + .97) * pSTP, color(na), bgcolor=llC))
            dPR.push(line.new(sBI + 1 + vpHO, pLST + (l + .0) * pSTP, sBI + int(adj_rpLN * rpW / 3) + 3 + vpHO, pLST + (l + .0) * pSTP, color=color.gray, width=2))
            sBI := sBI + int(adj_rpLN * rpW / 3) + 3 + vpHO
            eBI  = sBI - int(LpM * (int(adj_rpLN * rpW / 3) + 2))
            llC := color.from_gradient(LpM, 0, 1, color.new(mfpC, 53), color.new(chart.fg_color, 13))
            dRP.push(box.new(sBI, pLST + (l + .1) * pSTP, eBI, pLST + (l + .9) * pSTP, color(na), bgcolor=llC, text=vpLS != 'None' ? str.tostring(LpM * 100, format.percent) : '', text_color=LpM == 1 ? color.blue : LpM > .5 ? chart.bg_color : chart.fg_color, text_halign=text.align_right, text_size=LpM == 1 ? size.small : size.tiny))
    if spSH
        bbp = 2 * rpVSB.sum() - rpVST.sum()
        llC := bbp > 0 ? spBLC : spBRC
        dPR.push(line.new(sI + dfDist, pLST, sI + dfDist, pHST, color=llC, width=2))
    if vpSH
        dPR.push(line.new(b.i + int(4 * adj_rpLN * rpW / 3) + 1 + vpHO + dfDist, pLST, b.i + int(4 * adj_rpLN * rpW / 3) + 1 + vpHO + dfDist, pHST, color=mfpC, width=2))
        if npSH
            dPR.push(line.new(b.i + int(5 * adj_rpLN * rpW / 3) + 3 + vpHO + dfDist, pLST, b.i + int(5 * adj_rpLN * rpW / 3) + 3 + vpHO + dfDist, pHST, color=mfpC, width=2))
    if rpPL
        f_drawLabelX(vpSH ? b.i + int(4 * adj_rpLN * rpW / 3) + 1 + vpHO + dfDist : b.i + dfDist, pHST, 'Profile High · ' + str.tostring(pHST, format.mintick), label.style_label_down, mfpC, rpS, 'Profile High')
        f_drawLabelX(vpSH ? b.i + int(4 * adj_rpLN * rpW / 3) + 1 + vpHO + dfDist : b.i + dfDist, pLST, 'Profile Low · '  + str.tostring(pLST, format.mintick), label.style_label_up,   mfpC, rpS, 'Profile Low')
    vdMX = rpVSD.max()
    for l = 0 to rpNR - 1
        if dRP.size() < 500
            vtLV = rpVST.get(l), LpM = vtLV / vtMX, DpM = rpVSD.get(l) / vdMX
            if vpSH
                sBI  = b.i + int(4 * adj_rpLN * rpW / 3) + dfDist
                eBI  = sBI - int(LpM * adj_rpLN * rpW)
                llC := color.from_gradient(LpM, 0, 1, color.new(mfpC, 73), color.new(mfpC, 3))
                dRP.push(box.new(sBI + vpHO, pLST + (l + .1) * pSTP, eBI + vpHO, pLST + (l + .9) * pSTP, color(na), bgcolor=llC, text=(vpLS != 'None' ? str.tostring(array.get(rpVST, l), format.volume) : ''), text_halign=text.align_right, text_color=LpM == 1 ? color.yellow : chart.fg_color, text_size=vpS))
            if spSH
                sBI  = sI + dfDist, eBI = sBI + int(DpM * adj_rpLN * rpW)
                bbp  = 2 * rpVSB.get(l) - vtLV
                llC := bbp > 0 ? color.from_gradient(DpM, 0, 1, color.new(spBLC, 80), color.new(spBLC, 20)) : color.from_gradient(DpM, 0, 1, color.new(spBRC, 80), color.new(spBRC, 20))
                dRP.push(box.new(sBI + 1, pLST + (l + .1) * pSTP, eBI + 1, pLST + (l + .9) * pSTP, color(na), bgcolor=llC, text=(vpLS != 'None' ? str.tostring(bbp, format.volume) : ''), text_halign=text.align_left, text_color=chart.fg_color, text_size=vpS))
